version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    labels:
      - "dependencies"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      octokit:
        patterns:
          - "@octokit/*"
      typescript-eslint:
        patterns:
          - "typescript*"
          - "@typescript-eslint/*"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
